festcms/urls.py
import forms_builder.forms.urls

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
# from festflow import urls

admin.autodiscover()
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^forms/', include(forms_builder.forms.urls)),
    url(r'^', include('festflow.urls')),
    # url(r'^', include('volunteer.urls')),

    

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

festflow/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from . import views

urlpatterns = [
    # Home Page
    # Login link for the all users
    url(r'^adminlogin/$', views.admin_login, name='admin_login'),

    # logout for all and redirects to home page
    url(r'^adminlogout/$', views.admin_logout, name='admin_logout'),

    url(r'^$', views.index, name='index'),

    # About Page
    url(r'^about/$', views.about, name='about'),

    # Sponsors Page
    url(r'^sponsors/$', views.sponsors, name='sponsors'),

    # Contact Page
    url(r'^contact/$', views.contact, name='contact'),

    # Event Page
    url(r'^events/$', views.events, name='events'),

    # Keynotes Page
    url(r'^keynotes/$', views.keynotes, name='keynotes'),

    # Reach Us Page
    url(r'^reachus/$', views.reachus, name='reachus'),

    # Reach Us Page
    url(r'^collegelist/$', views.collegelist, name='collegelist'),

    # FAQ Page
    url(r'^faq/$', views.faq, name='FAQ'),
    url(r'^organizer/$', views.organizer, name='organizer'),

    # Subscribe Page
    url(r'^subscribe/$', views.subscribe, name='subscribe'),


    # Event View Page
    url(r'^events/(?P<event_identifier>[a-z]*)/$',
        views.event_view, name='event_view'),

    # Keynote View Page
    url(r'^keynote/(?P<keynote_identifier>[a-z]*)/$',
        views.keynote_view, name='keynote_view'),

    # Event Register Page
    url(r'^register_event/(?P<event_identifier>[a-z]*)/$',
        views.register_event, name='register_event'),

    # Login Page
    url(r'^login/$', views.login_page, name='login_page'),

    # social login urls
    url('', include('social_django.urls')),

    # Form to complete profile
    url(r'^complete_profile/$',
        views.complete_profile, name='complete_profile'),

    # logout url
    url(r'^logout/$',
        logout, {'next_page': '/'}),

   
    # Admin Page
    url(r'^adminhome/$', views.adminhome, name='adminhome'), 
    
    # About Page
    url(r'^adminabout/$', views.adminabout, name='adminabout'),

    # organizer Page
    url(r'^adminevent/$', views.adminevent, name='adminevent'),


    # organizer Page
    url(r'^adminorganizer/$', views.adminorganizer, name='organizer'),
    
    # Add About Page
    url(r'^adminaddabout/$', views.adminaddabout, name='adminaddabout'),

    # Add organizer
    url(r'^adminaddorganizer/$', views.adminaddorganizer, name='adminaddorganizer'),

    # Add event
    url(r'^adminaddevent/$', views.adminaddevent, name='adminaddevent'),

    # Add College List Page
    url(r'^adminaddcollegelist/$', views.adminaddcollegelist, name='adminaddcollegelist'),

    # Add Sponsours Page
    url(r'^adminaddsponsors/$', views.adminaddsponsors, name='adminaddsponsors'),

    # Add FAQ Page
    url(r'^adminaddfaq/$', views.adminaddfaq, name='adminaddfaq'),

   
    # Form to volunteer profile
    url(r'^volunteer_home/$',
        views.volunteer_home, name='volunteer_home'),

    # Event View Page
    url(r'^events/(?P<event_identifier>[a-z]*)/$',
        views.event_view, name='event_view'),


    

    
]

festflow/models.py
import hashlib

from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.urls import reverse, NoReverseMatch
from django.core.validators import RegexValidator, URLValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


lowercaseAlphabet = RegexValidator(
    r'^[a-z]*$', 'Only lower case alphabets are allowed.')


def validate_navbar_entry(url):
    domain = Site.objects.get_current().domain
    try:
        reverse(url)
    except NoReverseMatch:
        try:
            URLValidator()(url)
        except ValidationError:
            URLValidator()('https://%s%s' % (domain, url))
# Create your models here.


class Event(models.Model):
    "Stores information about the events in the fest"

    # event id
    identifier = models.CharField(max_length=50, unique=True,
                                  validators=[lowercaseAlphabet])

    # event name
    name = models.CharField(max_length=255)

    # event description
    description = models.TextField()

    # event logo
    logo = models.ImageField(upload_to='event_images/',
                             blank=True, null=True)

    # event problem statement file
    problem_statement_file = models.FileField(upload_to='problem_statements/',
                                              blank=True, null=True)
    fee = models.IntegerField(max_length=3,default=100)

    # event venue
    venue = models.CharField(max_length=255)
    venue_lat = models.DecimalField(max_digits=9, decimal_places=8,
                                    blank=True, null=True)
    venue_lon = models.DecimalField(max_digits=9, decimal_places=8,
                                    blank=True, null=True)

    # event date and time
    date_time = models.DateTimeField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/events/%s/' % self.identifier


class Keynote(models.Model):
    "Stores information about the keynote speech or talk in the fest"

    # keynote id
    identifier = models.CharField(max_length=50, unique=True,
                                  validators=[lowercaseAlphabet])

    # keynote name
    name = models.CharField(max_length=255)

    # keynote description
    description = models.TextField()

    # keynote image
    image = models.ImageField(upload_to='event_images/',
                              blank=True, null=True)

    # keynote venue
    venue = models.CharField(max_length=255)

    # keynote date and time
    date_time = models.DateTimeField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/keynote/%s/' % self.identifier


class College(models.Model):
    "Stores additional information about the user"
    # profile informations:
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Profile(models.Model):
    "Stores additional information about the user"

    # each profile is associated with a user
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # profile informations:
    institute_name = models.CharField(max_length=255)
    degree_name = models.CharField(max_length=255)
    major_subject_name = models.CharField(max_length=255)

    phone_number = models.CharField(max_length=15)

    # events registered for
    registered_events = models.ManyToManyField(Event)

    def __str__(self):
        return self.user.get_full_name()

    def get_absolute_url(self):
        return '/events/%s/' % self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    # create a dummy profile for superuser
    if created and instance.is_superuser:
        Profile.objects.create(user=instance)
        instance.profile.save()


class organizerMember(models.Model):
    """Stores information about the members of the organization
    that is conducting the fest"""

    name = models.CharField(max_length=100)

    position = models.CharField(max_length=100)

    rank = models.IntegerField(default=0)

    avatar_img = models.ImageField(upload_to='avatar_images/',
                                   blank=True, null=True)

    contactNumber = models.CharField(max_length=15)

    emailId = models.EmailField(blank=True, null=True)

    contactURL = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.name


class Sponsor(models.Model):
    """Stores information about fest sponsors
    """
    name = models.CharField(max_length=100)

    logo = models.ImageField(upload_to='sponsor_logos/')

    rank = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class About(models.Model):
    """Stores about content as raw html
    """
    identifier = models.CharField(max_length=50, unique=True)
    content = models.TextField()

    def __str__(self):
        return self.identifier

    class Meta:
        verbose_name = "about"
        verbose_name_plural = "about"


class NewsLetter(models.Model):
    """Stores newsletters sent to subscribed users
    """
    identifier = models.CharField(max_length=50, unique=True)
    content = models.TextField()

    def __str__(self):
        return self.identifier


class Subscription(models.Model):
    """Stores the details of subscribed users
    """
    identifier = models.CharField(max_length=50, unique=True)
    contact_email = models.EmailField(unique=True)

    def save(self, *args, **kwargs):
        """On save, add unique identifier
        """
        hasher = hashlib.md5(self.contact_email.encode())
        self.identifier = hasher.hexdigest()
        return super(Subscription, self).save(*args, **kwargs)

    def __str__(self):
        return self.contact_email


class FAQ(models.Model):
    """Stores the frequently asked questions
    """
    identifier = models.CharField(max_length=50, unique=True)
    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return self.identifier

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQs'


class NavbarEntry(models.Model):
    """Stores the navigation bar entries
    """
    url = models.CharField(default='#', max_length=100,
                           validators=[validate_navbar_entry])
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Navbar Entry'
        verbose_name_plural = 'Navbar Entries'
    
            
 

festflow/forms.py
from django.forms import ModelForm
from .models import *


class EditProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ['institute_name', 'degree_name',
                  'major_subject_name', 'phone_number']


class SubscriptionForm(ModelForm):

    class Meta:
        model = Subscription
        fields = ['contact_email']

festflow/templates/adminflow/about.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} ABOUT US {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/about.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h3 id='link'>About</h3>
        <div class="dash"></div>
        <br />
        <ul class="object-tools"> 
        <li> 
            <a href="/about" class="btn btn-info" role="button">Add about + </a>
            {% if content %}
                {% for i in content %}
                  <h4> {{ i.content }}</h4>
                {% endfor %}
            {% endif %}

            </li> </ul>
            



        

    </div>
</div>


{% endblock %}

festflow/templates/adminflow/addabout.html
{% extends "adminflow/base.html" %}
{% load static %}


{% block title %} ABOUT US {% endblock %}


{% block body_contents %}
   
    
<div class="container">
    <div class="jumbotron">

    	<h1>Add About </h1>

         <form class="form-inline" id="item_form" method="post"
             action="/admin/add_college/" enctype="multipart/form-data">

            {% csrf_token %}

      <table>
          <tr>
           
            <td>
              <label for="Identifier"><i>Identifier</i> </label>
            </td>  
            <td> 
                <input type="text" id="Identifier" class="form-control">
            </td>    
            </tr>
            <tr>
                <td>
                <label class="required" for="id_content"><i>Content</i> </label>                    
                </td>
                <td>
                <textarea name="=content" cols="40" rows="10" class="vLargeTextField" required id="id_content"></textarea>                    
                </td>
            </tr>
            <tr>
                <td>
                    
                </td>
                <td>
                  <button class="btn btn-info mb-2 waves-effect waves-light">Save <i class="fas fa-send ml-1"></i></button>
                    
                </td>
            </tr>
        </table>
        </form>

    </div>
    </div>



{% endblock %}

festflow/templates/adminflow/addevent.html
{% extends "adminflow/base.html" %}
{% load static %}


{% block body_contents %}
<div class="container">
    <div class="jumbotron">

    	<h2>Add Event </h2>

         <form class="form-item span8" id="item_form" method="post"
             action="/admin/add_event/" enctype="multipart/form-data">

            {% csrf_token %}          
            
            
                <div class="col-xs-3" >

                    <label for="identifier">Identifier:</label>
                    <input type="identifier" class="form-control" id="identifier">

                    <label for="name">Name:</label>
                    <input type="name" class="form-control" id="name">

                    <label for="description">Description:</label>
                    <textarea name="description" cols="40" rows="5" class="form-control" required="" id="id_description"></textarea> </br>

                    <label for="logo">Logo:</label>
                    <input type="file" name="logo" id="logo">

                    <label for="logo">Problem Statement:</label>
                    <input type="file" name="logo" id="logo">

                    <label for="fee">Fee:</label>
                    <input type="fee" class="form-control" id="fee">

                    <label for="venue">venue:</label>
                    <input type="venue" class="form-control" id="venue">

                    <label for="venue_lat">Venue Lat:</label>
                    <input type="number" name="venue_lat" value="0" class="form-control" required="" id="id_venue_lat">
                
                    <label for="venue_long">Venue Long:</label>

                    <input type="number" name="venue_long" value="0" class="form-control" required="" id="id_venue_long">


                    <div class="form-row field-date_time">
            
            
                <div>
                    
                    
                        <label class="required" for="id_date_time_0">Date time:</label>
                        
                            <p class="datetime">
                             Date: <input type="text" name="date_time_0" class="vDateField" size="10" required="" id="id_date_time_0"><span class="datetimeshortcuts">&nbsp;<a href="#">Today</a>&nbsp;|&nbsp;
                                <a href="#" id="calendarlink0"><span class="date-icon" title="Choose a Date"></span></a></span>
                                <br>
                                Time: <input type="text" name="date_time_1" class="vTimeField" size="8" required="" id="id_date_time_1"><span class="datetimeshortcuts">&nbsp;
                                <a href="#">Now</a>&nbsp;|&nbsp;<a href="#" id="clocklink0"><span class="clock-icon" title="Choose a Time"></span></a></span>


<br><span class="timezonewarning">Note: You are 5.5 hours ahead of server time.</span></p>
                        
                    
                    
                </div>
            
        </div>
                
                    
                    </br>
                    <button type="button" class="btn btn-primary">Save</button> 
                </div>
            </br>              

            
                







                



        </form>
    	


    </div>






</div>


{% endblock %}

festflow/templates/adminflow/base.html
<!DOCTYPE html>
{% load static %}

{% load navbar %}
<html>
<head>
    <title>{% block title %} Admin Home Page{% endblock %}</title>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- LOAD CSS AND BASIC JS -->

    <!-- Bootstrap minified css -->
    <link rel="stylesheet" type="text/css" href='{% static "css/bootstrap.min.css" %}'/>

    <!-- Main CSS -->
    <link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'/>

    <!-- Extra head block -->
    {% block extra_head %}

    {% endblock %}
</head>

<body>

    {% navbar %}

        <div class="container-fluid">
          <div class="row content">
            <div class="col-sm-2 sidenav hidden-xs">
              <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="/about">About</a></li>
                <li><a href="/event1">Events</a></li>
                <li><a href="/organizer">Event Organizer</a></li>
                 <li><a href="/college_list">College Details</a></li>
                 <li><a href="/sponsours">Sponsours</a></li>
                 
                <li><a href="/faq">FAQ</a></li>
              </ul><br>
            </div>  
            <div class="col-sm-9" >
                   
                    
            </div>
          </div>
        </div>
            


    <!-- Jquery minified js -->
    <script type="text/javascript" src='{% static "js/jquery.min.js"%}'></script>

    <!-- Bootstrap minified js -->
    <script type="text/javascript" src='{% static "js/bootstrap.min.js"%}'></script>

    <!-- extra JS -->
    {% block extrajs %}{% endblock %}
</body>
</html>

festflow/templates/adminflow/college_list.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} ABOUT US {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/about.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h3> College Details </h3>
        <div class="dash"></div>
        <br /> 

        <ul class="object-tools"> 
        <li> 
            <a href="/addcollegelist" class="btn btn-info" role="button">Add College List + 

        </br></a> 

            </br> <table class="table table-hover" >
            	<thead>
            		<tr>
            			<th scope="col">College Name</th>
      					<th scope="col"> Place</th>
      
  				</thead>
  				<tbody>
    				<tr>
      					<th scope="row">1</th>
      
    				</tr>
    
    
  				</tbody>
			</table>
		</li> 
	</ul>
            



        

    </div>
</div>


{% endblock %}

festflow/templates/adminflow/event1.html
{% extends "festflow/base.html" %}
{% load static %}



{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/about.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h3 id='link'>Organizer</h3>
        <div class="dash"></div>
        <br />
        <ul class="object-tools"> 
        <li> 
            <a href="/event1" class="btn btn-info" role="button">Add Event + </a>

            </li> </ul>
            



        

    </div>
</div>


{% endblock %}

festflow/templates/adminflow/faq.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} ABOUT US {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/about.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h3>FAQs</h3>
        
        <div class="dash"></div>
        <br />
        <ul class="object-tools"> 
        <li> 
            <a href="/addfaq" class="btn btn-info" role="button">Add FAQs + </a> </br>


            <table class="table table-hover" >
                <thead>
                    <tr>
                        <th scope="col">Identifier</th>
                        <th scope="col"> Question</th>
                         <th scope="col">Answer</th>
                        

      
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <th scope="row">hfkjfl</th>
                        <th scope="row">hfkjfl</th>

      
      
                    </tr>
                    
    
                </tbody>
            </table>
           



            </li> </ul>
            



        

    </div>
</div>


{% endblock %}

festflow/templates/adminflow/home.html
{% extends "adminflow/base.html" %}
{% load static %}

{% block body_contents %}

<div class="container">
    <div class="title">
        <div class="logo">
            <img src="{% static "images/logo.jpg" %}" class="img-circle" alt="Logo Brand">
        </div>
        <h1> ADVITIYA - 2019</h1>
        <h4> Welcome Admin... </h4>
        
    </div>
</div>


{% endblock %}

festflow/templates/adminflow/login_page.html
{% extends "adminflow/base.html" %}
{% load static %}

{% block title %} LOGIN {% endblock %}


{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        {% if user.is_authenticated %}
            <!--User is logged in-->
            <h1 id='link'>Login Details</h1>
            <div class="dash"></div>
            <br />
            <br />
            <div class='row'>
            <div class='col-lg-2'></div>
            <div class='col-lg-8'>
            <table class="table ">
                <tbody>
                    <tr>
                        <td>You are logged in as :</td>
                        <td><i> {{ user.username }}</i> !</td>
                    </tr>
                    <tr>
                        <td>First Name :</td>
                        <td><strong> {{ user.first_name }}</strong></td>
                    </tr>
                    <tr>
                        <td>Last Name :</td>
                        <td><strong> {{ user.last_name }}</strong></td>
                    </tr>
                    <tr>
                        <td>Email :</td>
                        <td><strong> {{ user.email }}</strong></td>
                    </tr>
                </tbody>
            </table>

            <a id='logout' href="/logout" class="btn" role="button">LOGOUT</a>
            </div>
            <div class='col-lg-2'></div>
            </div>

        {% else %}
            <!--User is not logged in-->
              <!-- /.login-logo -->
              <div class="login-box-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form id="login_form" method="post" action="/adminlogin/">
                {% csrf_token %}
                  <div class="form-group has-feedback">
                    <input type="text" class="form-control" name="username" placeholder="Username" required="">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                  </div>
                  <div class="form-group has-feedback">
                    <input type="password" class="form-control" name="password" placeholder="Password" required="">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                  </div>
                  <div class="row">
                    <div class="col-md-4"></div>
                    <div class="text-center col-md-4">
                      <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <div class="col-md-4"></div>
                    <!-- /.col -->
                  </div>
                </form>
            </div>
        {% endif %}

    </div>
</div>

{% endblock %}

festflow/templates/adminflow/navbar.html
{% load static %}


<nav class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="logo">
        <a href="/">
          <img src="{% static "images/logo.png" %}" alt="Logo Brand" height='50px'>
        </a>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">

        <li><a href="/about">About us</a></li>
        <li><a href="/reachus">Reach us</a></li>
        <li><a href="/sponsors">sponsors</a></li>
        <li><a href="/faq">faq</a></li>
        <li><a href="/event1">Event Details</a></li>

        {% if user.is_authenticated %}

        <li><a href="/logout">Logout</a></li>

        {% else %}
        <li><a href="/login">User</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

festflow/templates/adminflow/organizer.html
{% extends "festflow/base.html" %}
{% load static %}

{% block title %} ABOUT US {% endblock %}

{% block extra_head %}

<!-- View CSS -->
<link rel="stylesheet" type="text/css" href='{% static "css/about.css" %}'/>

{% endblock %}

{% block body_contents %}

<div class="container">
    <div class="jumbotron">
        <h3 id='link'>Organizer</h3>
        <div class="dash"></div>
        <br />
        <ul class="object-tools"> 
        <li> 
            <a href="/addorganizer" class="btn btn-info" role="button">Add Organizer + </a>

            </li> </ul>
            



        

    </div>
</div>


{% endblock %}